ALTER TABLE SLOT DROP CONSTRAINT UK_01_PERSON_ID_START_AT;

ALTER TABLE SLOT DROP COLUMN START_AT;

ALTER TABLE SLOT ADD COLUMN (
    SLOT_DATE DATE NOT NULL,
    SLOT_HOUR SMALLINT NOT NULL
);

COMMENT ON COLUMN SLOT.SLOT_DATE IS 'Slot Date';
COMMENT ON COLUMN SLOT.SLOT_HOUR IS 'Slot Hour';

ALTER TABLE SLOT ADD CONSTRAINT UK_01_PERSON_ID_START_AT UNIQUE (PERSON_ID, SLOT_DATE, SLOT_HOUR);


