# Server
server:
    port: ${INTERVIEW_CALENDAR_API_SERVER_PORT:8080}
    servlet:
        context-path: /interview-calendar-api
# Spring
spring:
    main:
        allow-bean-definition-overriding: true
    application:
        name: interview-calendar-api
    # Profile
    profiles:
        active: ${INTERVIEW_CALENDAR_API_PROFILE_ACTIVE:h2}
    liquibase:
        change-log: classpath:/db/liquibase.xml
    messages:
        basename: messages

# Logging
logging:
    level:
        liquibase: INFO

# Swagger
swagger:
    info:
        api:
            version: 0.0.1
