# Server
server:
    port: 8080
    servlet:
        context-path: /interview-calendar-api
# Spring
spring:
    application:
        name: interview-calendar-api
    # Profile
    profiles:
        active: ${INTERVIEW_CALENDAR_API_PROFILE_ACTIVE:h2}
    # Liquibase
    liquibase:
        change-log: classpath:/db/liquibase.xml
